name: BuildUHC
main: org.sobadfish.builduhc.BuildUHCMain
version: 1.0.0
api:
  - 1.0.11
  - 3.0.0
author: sobadfish&GouDang888
load: POSTWORLD
description: "BuildUHC"

softdepend:
  - ScoreboardPlugin

loadbefore:
  - ScoreboardPlugin
